source:
  type: snowflake
  config:
    account_id: "MPXFEBG-AP40156"
    username: "akaragkiozakis"
    password: "Akaragkiozakis123"
    database_pattern:
      allow:
        - "DATAHUB_DEMO"
    include_table_lineage: true
    include_view_lineage: true
    profiling:
      enabled: false

sink:
  type: datahub-rest
  config:
    server: "http://localhost:8080"