
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique:
              config:
                severity: warn
          - not_null:
              config:
                severity: warn

  - name: fred_clean
    description: "Cleaned FRED data with standardized types"
    columns:
      - name: series_id
        description: "FRED series identifier"
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["GDPC1", "CPIAUCSL", "PCE", "UNRATE", "INDPRO", "FEDFUNDS"]
      - name: observation_date
        description: "Date of observation"
        data_tests:
          - not_null
      - name: value
        description: "Numeric value"
        data_tests:
          - not_null
      - name: file_load_date
        description: "Ingestion date"

  - name: yearly_averages
    description: "Average annual values per indicator"
    columns:
      - name: series_id
        data_tests:
          - not_null
      - name: indicator_name
        data_tests:
          - not_null
      - name: year
        data_tests:
          - not_null
      - name: avg_value
        data_tests:
          - not_null

  - name: yoy_changes
    description: "Year-over-year percentage changes per indicator"
    columns:
      - name: series_id
        data_tests:
          - not_null
      - name: indicator_name
        data_tests:
          - not_null
      - name: year
        data_tests:
          - not_null
      - name: yoy_change_pct
        data_tests: []

  - name: real_interest_rates
    description: "Real interest rate = Fed Funds - Inflation"
    columns:
      - name: year
        data_tests:
          - not_null
      - name: inflation_rate
        data_tests:
          - not_null
      - name: fed_funds_rate
        data_tests:
          - not_null
      - name: real_interest_rate
        data_tests:
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique:
              config:
                severity: warn
          - not_null:
              config:
                severity: warn

sources:
  - name: raw
    description: "Raw data sources from various APIs"
    schema: raw
    tables:
      - name: fred_data
        identifier: FRED_DATA
        description: "Raw FRED economic data from Federal Reserve API"
        columns:
          - name: series_id
            description: "FRED series identifier (e.g., GDPC1, UNRATE)"
          - name: indicator_name
            description: "Human-readable name of the economic indicator"
          - name: observation_date
            description: "Date of the economic observation"
          - name: value
            description: "Numeric value of the economic indicator"
          - name: file_load_date
            description: "Date when the data was loaded from JSON files"
